---
title: "My map"
author: "ZIYAO WANG (Billy)"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
      number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F)
Sys.setlocale("LC_ALL","English")
```

```{r load-lib, message=FALSE}
library(tidyverse)
library(sf)
library(tmap)
library(geogrid)
library(cartogram)
library(maptools)
```

# 2022 Election data (House of representatives - Two party preferred by division)

## VIC Maps

```{r vic-map}
vic_elect_map <- read_sf(here::here("data/vic-july-2021-esri/E_VIC21_region.shp")) %>% 
  select(-c(Total_Popu, Australian)) %>% 
  st_make_valid(geometry) %>% 
  mutate(centroid = st_centroid(geometry))

vic_elect_data <- read.csv(here::here("data/2022Election_HouseTppByDivision.csv")) %>% 
  filter(StateAb == "VIC")

vic_mapdata <- left_join(vic_elect_data,vic_elect_map,
                      by = c("DivisionNm" = "Elect_div"))

ggplot(vic_mapdata, aes(fill =  PartyAb))+
  geom_sf(aes(geometry = geometry))+
  guides(fill = guide_legend("Party"))+
  theme_void() + 
  theme(legend.position="bottom")

ggplot(vic_mapdata) + 
  geom_sf(aes(geometry = geometry)) + 
  geom_sf(aes(geometry = centroid, color = PartyAb)) +
  guides(color = guide_legend("Party"))+
  theme_void() + 
  theme(legend.position="bottom")

```

### Hex Maps using `geogrid` - VIC Election

```{r vic-hex}
vic_hex <- st_as_sf(vic_mapdata)

for (i in 1:6) {
  new_cells_vic <- calculate_grid(shape = vic_hex, grid_type = "hexagonal", seed = i)
  plot(new_cells_vic, main = paste("Seed", i, sep = " "))
}

new_vic_hex <- calculate_grid(shape = vic_hex, grid_type = "hexagonal", seed = 5)
result_vic_hex <- assign_polygons(vic_hex, new_vic_hex)

tm_shape(result_vic_hex) + 
  tm_polygons("TotalVotes", palette = "viridis") +
  tm_text("PartyAb")
```



## National Maps

```{r au-map}
sf_use_s2(T)
aec_map <- read_sf(here::here("data/Cwlth_electoral_boundaries_ESRI/2021_ELB_region.shp")) %>% 
  select(-c(Total_Popu, Australian)) %>% 
  st_make_valid(geometry) %>% 
  mutate(centroid = st_centroid(geometry))

aec_data <- read.csv(here::here("data/2022Election_HouseTppByDivision.csv"))

aec_mapdata <- left_join(aec_data,aec_map,
                      by = c("DivisionNm" = "Elect_div"))

ggplot(aec_mapdata, aes(fill =  PartyAb))+
  geom_sf(aes(geometry = geometry))+
  guides(fill = guide_legend("Party"))+
  theme_void() + 
  theme(legend.position="bottom")

ggplot(aec_mapdata) + 
  geom_sf(aes(geometry = geometry)) + 
  geom_sf(aes(geometry = centroid, color = PartyAb)) +
  guides(color = guide_legend("Party"))+
  theme_void() + 
  theme(legend.position="bottom")
```

### Hex Maps using `geogrid` - Australian Election

```{r au-hex}
au_hex <- st_as_sf(aec_mapdata)

for (i in 1:6) {
  new_cells_au <- calculate_grid(shape = au_hex, grid_type = "hexagonal", seed = i)
  plot(new_cells_au, main = paste("Seed", i, sep = " "))
}

new_au_hex <- calculate_grid(shape = au_hex, grid_type = "hexagonal", seed = 5)
result_au_hex <- assign_polygons(au_hex, new_au_hex)

tm_shape(result_au_hex) + 
  tm_polygons("TotalVotes", palette = "viridis") +
  tm_text("PartyAb")
```

### Non-contiguous Area Cartogram - using `cartogram`


```{r}

au <- st_transform(au_hex, crs = "+init=epsg:3112")

au_sf_cont1 <- cartogram_cont(au_sf_cont, "TotalVotes", 3)
au_sf_cont2 <- cartogram_cont(au_sf_cont1, "TotalVotes", 15) # was using 18 

tm_shape(au_sf_cont2) + tm_polygons("TotalVotes", style = "jenks", legend.show = FALSE) +
  tm_layout(frame = FALSE)
```

Using result from `cartogram` on `geogrid` to check if the `calculation_grid` function can be improved.

```{r try-improve}
new_cart_hex <- calculate_grid(shape = au_sf_cont2, grid_type = "hexagonal", seed = 5)
result_cart_hex <- assign_polygons(au_sf_cont2, new_cart_hex)

tm_shape(result_cart_hex) + 
  tm_polygons("StateAb", palette = "viridis") +
  tm_text("PartyAb")+
  tm_layout(legend.outside= T)

```


