---
title: "Project-Schedule"
author: "ZIYAO WANG (Billy)"
date: "`r Sys.Date()`"
output: html_document
---

# ETC5543 Creativity Project - "hexmap"

BY **ZIYAO WANG (Billy)**

Week 1 (7/11-15) - Summarizing relevant research articles or information.

Week 2 (7/18-22) - Wide range of research on relevant information and literature reviews.

Week 3 (7/25-29) - Attempts to map both Australia Census (2021) and Election data (2022) with `sf` R package.

Data Sources:  
  
  * Census data (2021)
  
    [Data Packages](https://www.abs.gov.au/census/find-census-data/datapacks?release=2021&product=GCP&geography=SA1&header=S)            
    [Geo Packages](https://www.abs.gov.au/census/find-census-data/geopackages)

  * Election Data [2022](https://www.aec.gov.au/Electorates/gis/gis_datadownload.htm)

Week 4 (8/1-5) - Producing geographic maps for both Census & Election data sets (separately).

Week 5 (8/8-12) - Present the project progress & produce the hex maps for 2022 Australia Election data.

Week 6 (8/15-19) - Research a way to expand the original geographic map to multiple hex tiles for each region/area.    

Week 7 (8/22-26) - Read and understand the relevant documents of "Hungarian algorithm" in `geogrid` [package](https://github.com/jbaileyh/geogrid), then try to adjust the **cost** function while assigning hex-tile in the algorithm (i.e. considering squared distance instead of the absolute value, and aim for multiple iteration for better solution instead of the optimal/best one).

Week 8 (8/29-9/2) - Learn the Rcpp and the relevant packages in R to understand the "Hungarian algorithm". Meanwhile, researching in general for suitable algorithms in solving quadratic problems such as "Genetic Algorithms".   

Week 9 onward (9/5- present) - Adjusting the parameters in the distortion of the geographical map function to obtain better input map data. Following with the use of the `calculate_grid` function in `geogrid` to examine and identify the quality of distortions.


